name: Dead code checks

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop_commenting-code

jobs:
  dead-code-detection:
    runs-on: ubuntu-latest

    env:
      TARGET_DIR: beacon

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install vulture

      - name: Check dead code
        run: python scripts/check_dead_code.py "$TARGET_DIR"